export const theme = {
  colors: {
    accent: '#1E3A8A',
    background: '#F3F4F6',
    white: '#FFFFFF',
    text: {
      primary: '#0F172A',
      secondary: '#111827',
      tertiary: '#6B7280',
      quaternary: '#9CA3AF',
    },
    error: {
      primary: '#DC2626',
      secondary: '#991B1B',
      background: '#FEF2F2',
      border: '#FECACA',
      light: '#F97373',
    },
    border: {
      light: '#E5E7EB',
      medium: '#D1D5DB',
    },
    tag: {
      background: '#EEF2FF',
      text: '#1E3A8A',
    },
    code: {
      background: '#F3F4F6',
      border: '#E5E7EB',
    },
  },
  spacing: {
    xs: 4,
    sm: 6,
    md: 8,
    lg: 10,
    xl: 12,
    xxl: 14,
    xxxl: 16,
    huge: 18,
    massive: 20,
    giant: 24,
    enormous: 28,
    colossal: 32,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 18,
    full: 999,
  },
  fontSize: {
    xs: 11,
    sm: 12,
    md: 13,
    base: 14,
    lg: 15,
    xl: 16,
    xxl: 17,
    xxxl: 18,
    huge: 22,
    massive: 24,
    giant: 26,
  },
  shadow: {
    small: {
      shadowColor: '#000',
      shadowOpacity: 0.06,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 10,
      elevation: 2,
    },
  },
};